### ISSUE TITLE
Array type property translation wrong

### ISSUE THREAD

**Issue by xuemduan** [citiususc/jsonschema2shacl#4]
The array type property needs to be translated to a property first, then based on its items to see whether needs to create more shapes, but the current translation directly creates a node shape which is not correct.

For example, if we have 
```
"P":{
			"type": "array",
			"items": {"type": "string"}},
```

what we need to create is just 

```
PS a sh:PropertyShape ;
    sh:path :P  .
```

**Comment by osm0512** [comment]
@xuemduan @dachafra I've fixed both issues. Whenever you can, please check if it's alright now.

**Comment by xuemduan** [comment]
> @xuemduan @dachafra I've fixed both issues. Whenever you can, please check if it's alright now.

It works well now:)

**Comment by dachafra** [comment]
Thank you very much @osm0512
